name: Close Invalid Issues

on:
  issues:
    types: [labeled]

jobs:
  close_invalid_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Close invalid issues
      run: node  .github/actions/close_invalid_issues.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
