name: Fermer les problèmes invalides

on:
  workflow_dispatch:

jobs:
  close_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node ./action/close_invalid_issues.ts
      env:
        ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
